name: Build on archlinux

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  meson-build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        pacman -Syu --noconfirm arch-install-scripts
        pacman-key --init
        pacman-key --populate archlinux

    - name: Update package databases
      run: pacman -Sy

    - name: Install dep
      run: |
        pacman -S --noconfirm base-devel meson pkgconfig wlroots wayland wayland-protocols libdrm systemd libxcb xcb-util-wm libxml2 cairo pango libxpm libjpeg-turbo librsvg
        pacman -S --noconfirm clang ninja cppcheck doxygen graphviz libxslt xmlto wlr-protocols

    - name: Build with Meson
      run: |
        meson builddir -Dxwayland=enabled
        ninja -C builddir

    - name: Run cppcheck
      run: cppcheck --project=builddir/compile_commands.json
