name: Build on archlinux

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  BUILD_TYPE: Release

jobs:
  meson-build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        pacman -Syu --noconfirm arch-install-scripts
        pacman-key --init
        pacman-key --populate archlinux

    - name: Update package databases
      run: pacman -Sy

    - name: Install dep
      run: |
        pacman -S --noconfirm \
          base-devel \
          meson \
          pkgconfig \
          wayland \
          wayland-protocols \
          wlroots0.21 \
          wlr-protocols \
          libxcb \
          xcb-util-wm \
          clang \
          ninja \
          cppcheck \
          doxygen \
          graphviz \
          libxslt \
          xmlto \
          libxml2 \
          cairo \
          pango \

    - name: Install wlframe
      run: |
        pacman -S --noconfirm \
          libpng \
          libjpeg-turbo	\
          git

        git clone https://github.com/zzxyb/wlframe.git /tmp/wlframe
        cd /tmp/wlframe
        meson setup builddir --prefix=/usr
        ninja -C builddir
        ninja -C builddir install

    - name: Install tomlc99
      run: |
        git clone https://github.com/cktan/tomlc99.git /tmp/tomlc99
        cd /tmp/tomlc99
        make
        make install prefix=/usr

    - name: Build with Meson
      run: |
        meson builddir -Dxwayland=enabled
        ninja -C builddir

    - name: Run cppcheck
      run: cppcheck --project=builddir/compile_commands.json
